{% set name = "aiofiles" %}
{% set version = "0.4.0" %}
{% set sha256 = "021ea0ba314a86027c166ecc4b4c07f2d40fc0f4b3a950d1868a0f2571c2bbee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - aiofiles

about:
  home: https://github.com/Tinche/aiofiles
  summary: "File support for asyncio"
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - kszucs
    - carlodri
