{% set name = "aiofiles" %}
{% set version = "25.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiofiles-{{ version }}.tar.gz
  sha256: a8d728f0a29de45dc521f18f07297428d56992a742f0cd2701ba86e44d23d5b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - aiofiles

about:
  home: https://github.com/Tinche/aiofiles
  summary: File support for asyncio
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache

extra:
  recipe-maintainers:
    - xylar
    - kszucs
    - carlodri
