{% set name = "aiofiles" %}
{% set version = "23.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiofiles-{{ version }}.tar.gz
  sha256: 7a321e787cb3839e7d70f56121bf9197a1980609a0fe06a6f96c573406ce4fca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7

test:
  imports:
    - aiofiles

about:
  home: https://github.com/Tinche/aiofiles
  summary: File support for asyncio
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache

extra:
  recipe-maintainers:
    - xylar
    - kszucs
    - carlodri
