travis:
  secure:
    BINSTAR_TOKEN: dnR1QQLMP/I5O54gY3hfk62DjhSiQJ8g8P7QQ5MnDtsE0i2A2Deyex4aQ8I58bb3h/UJp1gtg5gWMiilVDB9dyyxFuvtEdgeBT+5MssECicsRAB7YTtWNp1vAu9k02z8xk58koQb4bX5ZFjdsfQHKyanoMQG8Ryn135iTRdhXJ18hcGQh3WarMOEiod2AgI2ZrNa+98VkCxmhgUVPn8rZxzaH8lj8C5+Kpf8SRAro9Is/FzXwFE5jbXNOBX3i3IaV+9lbtFSN/GpkeK3TYvp96/o7DO/VlQ7lalz6OlDJgZuI7hqeiadm7IJZvDP2my46gFWYOq7sm+nIGS9mJnRObwbxGr8ABzvg6NTGgJPlnOwIB2i0WdLX/4YWV8s9E3rkyBySNguQaFFUEydjQal8kmVIDOfRZm1GSDUX0Bw23If0bMC67p8yxUjNa+u0Ct6OkxcO625lbLYQbPIEKEdQ7sySPJ6LnaanPuyDxiL7BWt7WtBiQUjm+SsULMqLT2JdBLWUwb3eTCnyfj4I/fPBDewg/6SUEA0hHkgvu95tfgtpvlhFf53ItTbmnxjt2SISZWOugUIsE3tqKzFBSc53uHq8sCeQUSqYkzVTnfRA6vh/qexRHZNVtZdZnHVwg1sAKeWknNpsfAeL3EZSRcxH/UPX/57GiGAswODqwkKGbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
